CREATE TABLE Users
(
	UserId INT IDENTITY PRIMARY KEY NOT NULL,
	Username NVARCHAR(20) UNIQUE NOT NULL,
	Password NVARCHAR(20) CHECK(LEN(Password) >= 5) NOT NULL,
	FullName NVARCHAR(50) NOT NULL,
	LastLogin DATE
)
GO
